auth_subdomain: true
headers:
  Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
  X-XSS-Protection: "1; mode=block"
  Content-Security-Policy: "default-src 'self';"
  X-Frame-Options: "SAMEORIGIN"